### ISSUE TITLE
无法打开 并且微云链接失效

### ISSUE THREAD

**Issue by thwfhk** [wzpan/BeamerStyleSlides#4]
在github上下载的显示损坏无法打开，微云下载链接已经失效，请求更新🥺

**Comment by wzpan** [comment]
你可以安装 [git-lfs 2.2](https://github.com/git-lfs/git-lfs/releases/tag/v2.2.0) 然后再 git clone 整个仓库。

**Comment by thwfhk** [comment]
安装后clone仍然无法打开，git-lfsb版本显示如下：
```
❯ git-lfs
git-lfs/2.2.0 (GitHub; darwin amd64; go 1.8.3; git a99f4b21)
git lfs <command> [<args>]
```

**Comment by wzpan** [comment]
重新生成了一下分享链接。看看是否可以下载：
keynote：https://share.weiyun.com/del3tuMG
PPT：https://share.weiyun.com/hOm6pu4y

**Comment by thwfhk** [comment]
下载成功了，感谢！
