### ISSUE TITLE
author 和 title 没有办法通过编辑模板来修改

### ISSUE THREAD

**Issue by HenryDong99** [wzpan/BeamerStyleSlides#7]
rt，作者大大，如何才能修改author和title？当我编辑母板时点不动底部的author和title，WPS2019版和PPT2021LSTC版都试过。

**Comment by wzpan** [comment]
为什么要编辑模版里的字段？你应该只改 data 里的数据就可以

**Comment by HenryDong99** [comment]
感谢作者大大，可以了。
